//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpanseReportManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpanseReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpanseReport()
        {
            this.Expanses = new HashSet<Expans>();
        }
    
        public System.Guid ExpanseReport_ID { get; set; }
        public System.Guid Employee_ID { get; set; }
        public System.Guid Author_ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int StatusCode { get; set; }
        public Nullable<System.DateTime> ManagerValidationDate { get; set; }
        public Nullable<System.DateTime> AccountingValidatationDate { get; set; }
        public double Total_HT { get; set; }
        public double Total_TVA { get; set; }
        public double Total_TTC { get; set; }
        public string ManagerComment { get; set; }
        public string AccountingComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expans> Expanses { get; set; }
    }
}
